import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class jab {
    public static void main(String[] args) throws IOException {
        Path outputPath = Paths.get("web.html");
        String html = buildBusinessWebsiteHtml();
        Files.writeString(outputPath, html);
        System.out.println("Generated business website at: " + outputPath.toAbsolutePath());
    }

    private static String buildBusinessWebsiteHtml() {
        return "<!DOCTYPE html>\n"
            + "<html lang=\"en\">\n"
            + "  <head>\n"
            + "    <meta charset=\"UTF-8\" />\n"
            + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
            + "    <title>Northstar Advisory | Business Growth Studio</title>\n"
            + "    <meta name=\"description\" content=\"Northstar Advisory is a professional business growth studio helping brands scale with strategy, digital transformation, and high-converting marketing systems.\" />\n"
            + "    <link rel=\"stylesheet\" href=\"mass.css\" />\n"
            + "    <style>\n"
            + "      body { line-height: 1.6; }\n"
            + "      a { color: inherit; }\n"
            + "      .section { padding: 16px 0; }\n"
            + "      .section-head { max-width: 680px; margin: 0 auto 28px; text-align: center; }\n"
            + "      .eyebrow { display: inline-block; margin-bottom: 12px; padding: 7px 12px; border-radius: 999px; background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.2); color: var(--text-2); font-size: 0.76rem; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; }\n"
            + "      .section-head h2 { margin: 0; font-size: clamp(2rem, 2.6vw, 3rem); letter-spacing: -0.05em; }\n"
            + "      .section-head p { color: var(--text-2); margin-top: 10px; }\n"
            + "      .services-grid, .process-grid, .testimonials-grid, .pricing-grid, .feature-grid { display: grid; gap: 22px; }\n"
            + "      .services-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }\n"
            + "      .process-grid { grid-template-columns: repeat(4, minmax(0, 1fr)); }\n"
            + "      .testimonials-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }\n"
            + "      .pricing-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }\n"
            + "      .feature-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }\n"
            + "      .service-card, .process-card, .testimonial, .price-card, .feature-card { min-height: 100%; }\n"
            + "      .icon-box { width: 52px; height: 52px; display: grid; place-items: center; border-radius: 16px; margin-bottom: 18px; background: linear-gradient(135deg, rgba(174,220,255,0.25), rgba(255,255,255,0.08)); border: 1px solid rgba(255,255,255,0.18); font-size: 1.4rem; box-shadow: inset 0 1px 0 rgba(255,255,255,0.15); }\n"
            + "      .service-card h3, .process-card h3, .feature-card h3, .price-card h3 { margin: 0 0 10px; font-size: 1.2rem; }\n"
            + "      .service-card p, .process-card p, .feature-card p, .price-card p, .testimonial p { margin: 0; color: var(--text-2); }\n"
            + "      .process-step { display: inline-flex; align-items: center; justify-content: center; width: 40px; height: 40px; border-radius: 50%; margin-bottom: 18px; background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.16); font-weight: 700; }\n"
            + "      .quote-mark { font-size: 2.8rem; line-height: 1; color: rgba(255,255,255,0.55); margin-bottom: 10px; }\n"
            + "      .testimonial-footer { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-top: 18px; padding-top: 16px; border-top: 1px solid rgba(255,255,255,0.12); }\n"
            + "      .person { display: flex; align-items: center; gap: 12px; }\n"
            + "      .avatar { width: 42px; height: 42px; border-radius: 50%; display: grid; place-items: center; font-weight: 700; background: linear-gradient(135deg, rgba(168,217,255,0.5), rgba(255,255,255,0.1)); border: 1px solid rgba(255,255,255,0.2); }\n"
            + "      .person small { color: var(--text-3); }\n"
            + "      .price-card { display: flex; flex-direction: column; }\n"
            + "      .price-card .price { margin: 18px 0 8px; font-size: 2.2rem; font-weight: 800; letter-spacing: -0.05em; }\n"
            + "      .price-card ul { list-style: none; padding: 18px 0 0; margin: 0; color: var(--text-2); }\n"
            + "      .price-card li { position: relative; padding-left: 24px; margin-bottom: 10px; }\n"
            + "      .price-card li::before { content: \"✓\"; position: absolute; left: 0; color: #9fe0d2; font-weight: 700; }\n"
            + "      .featured { position: relative; border-color: rgba(165,214,255,0.8); box-shadow: 0 18px 32px rgba(91,160,255,0.18); }\n"
            + "      .featured-badge { position: absolute; top: 18px; right: 18px; padding: 6px 10px; border-radius: 999px; background: rgba(159,224,210,0.2); border: 1px solid rgba(159,224,210,0.5); color: #d7faf1; font-size: 0.7rem; font-weight: 700; text-transform: uppercase; }\n"
            + "      .split-layout { display: grid; grid-template-columns: 1.1fr 0.9fr; gap: 22px; }\n"
            + "      .split-copy { padding: 10px 0; }\n"
            + "      .check-list { list-style: none; padding: 0; margin: 24px 0 0; display: grid; gap: 14px; }\n"
            + "      .check-list li { position: relative; padding-left: 30px; color: var(--text-2); }\n"
            + "      .check-list li::before { content: \"•\"; position: absolute; left: 0; color: #9fe0d2; font-size: 1.8rem; line-height: 1; }\n"
            + "      .metrics-wrap { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 18px; }\n"
            + "      .metric { padding: 24px 20px; text-align: center; }\n"
            + "      .metric strong { display: block; font-size: clamp(1.8rem, 2vw, 2.5rem); }\n"
            + "      .metric span { color: var(--text-3); }\n"
            + "      .cta-box { padding: 30px; display: flex; align-items: center; justify-content: space-between; gap: 20px; flex-wrap: wrap; }\n"
            + "      .cta-box h3 { margin: 0; font-size: clamp(1.6rem, 2vw, 2.3rem); }\n"
            + "      .cta-box p { margin: 6px 0 0; color: var(--text-2); }\n"
            + "      .mini-logo { display: inline-flex; align-items: center; gap: 12px; margin-bottom: 16px; }\n"
            + "      .footer-grid { display: grid; grid-template-columns: 1.3fr 0.7fr 0.7fr 0.9fr; gap: 22px; }\n"
            + "      .footer-grid h4 { margin: 0 0 14px; font-size: 1rem; }\n"
            + "      .footer-grid p, .footer-grid a, .footer-grid li { color: var(--text-2); }\n"
            + "      .footer-links { list-style: none; padding: 0; margin: 0; display: grid; gap: 8px; }\n"
            + "      @media (max-width: 980px) { .services-grid, .process-grid, .testimonials-grid, .pricing-grid, .footer-grid, .split-layout, .metrics-wrap, .feature-grid { grid-template-columns: 1fr 1fr; } }\n"
            + "      @media (max-width: 760px) { .services-grid, .process-grid, .testimonials-grid, .pricing-grid, .footer-grid, .split-layout, .metrics-wrap, .feature-grid { grid-template-columns: 1fr; } .nav { width: 100%; justify-content: center; } .cta-box { align-items: flex-start; } }\n"
            + "    </style>\n"
            + "  </head>\n"
            + "  <body>\n"
            + "    <div class=\"page-shell\">\n"
            + "      <header class=\"glass topbar\">\n"
            + "        <div class=\"brand\">\n"
            + "          <span class=\"brand-mark\"></span>\n"
            + "          <span>Northstar Advisory</span>\n"
            + "        </div>\n"
            + "        <nav class=\"nav\" aria-label=\"Main navigation\">\n"
            + "          <a href=\"#services\">Services</a>\n"
            + "          <a href=\"#about\">About</a>\n"
            + "          <a href=\"#process\">Process</a>\n"
            + "          <a href=\"#pricing\">Pricing</a>\n"
            + "          <a href=\"#contact\">Contact</a>\n"
            + "        </nav>\n"
            + "        <a class=\"glass-button primary\" href=\"#contact\">Book a consult</a>\n"
            + "      </header>\n"
            + "      <main>\n"
            + "        <section class=\"glass hero\">\n"
            + "          <div class=\"hero-copy\">\n"
            + "            <div class=\"eyebrow\">Growth strategy • digital transformation</div>\n"
            + "            <h1 class=\"heading\">Turn momentum into measurable business growth.</h1>\n"
            + "            <p class=\"subtitle\">We help founders, operators, and executive teams sharpen their strategy, modernize their customer experience, and launch systems that scale with confidence.</p>\n"
            + "            <div class=\"hero-actions\">\n"
            + "              <a class=\"glass-button primary\" href=\"#contact\">Schedule strategy call</a>\n"
            + "              <a class=\"glass-button secondary\" href=\"#services\">Explore services</a>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "          <div class=\"hero-visual\">\n"
            + "            <div class=\"orb\" aria-hidden=\"true\"></div>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "        <section class=\"section\">\n"
            + "          <div class=\"glass stats\">\n"
            + "            <div class=\"glass-card stat\">\n"
            + "              <span class=\"stat-value\">+184%</span>\n"
            + "              <span class=\"stat-label\">Average pipeline growth</span>\n"
            + "            </div>\n"
            + "            <div class=\"glass-card stat\">\n"
            + "              <span class=\"stat-value\">3.2x</span>\n"
            + "              <span class=\"stat-label\">Return on transformation spend</span>\n"
            + "            </div>\n"
            + "            <div class=\"glass-card stat\">\n"
            + "              <span class=\"stat-value\">92%</span>\n"
            + "              <span class=\"stat-label\">Client retention rate</span>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "        <section id=\"services\" class=\"section\">\n"
            + "          <div class=\"section-head\">\n"
            + "            <span class=\"eyebrow\">What we do</span>\n"
            + "            <h2>Full-spectrum support for ambitious businesses.</h2>\n"
            + "            <p>From strategic positioning to execution systems, we provide the clarity, design, and operational discipline needed to grow without chaos.</p>\n"
            + "          </div>\n"
            + "          <div class=\"services-grid\">\n"
            + "            <article class=\"glass glass-card service-card\">\n"
            + "              <div class=\"icon-box\">📈</div>\n"
            + "              <h3>Business Strategy</h3>\n"
            + "              <p>Positioning, market analysis, KPI frameworks, and roadmap planning built to accelerate sustainable growth.</p>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card service-card\">\n"
            + "              <div class=\"icon-box\">⚙️</div>\n"
            + "              <h3>Operational Systems</h3>\n"
            + "              <p>Process design, team alignment, and automation strategies that reduce friction and improve delivery speed.</p>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card service-card\">\n"
            + "              <div class=\"icon-box\">🎯</div>\n"
            + "              <h3>Marketing Performance</h3>\n"
            + "              <p>Funnel strategy, campaign planning, conversion optimization, and reporting systems for qualified demand generation.</p>\n"
            + "            </article>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "        <section id=\"about\" class=\"section\">\n"
            + "          <div class=\"split-layout\">\n"
            + "            <div class=\"glass glass-panel split-copy\">\n"
            + "              <span class=\"eyebrow\">Why Northstar</span>\n"
            + "              <h2 class=\"heading\" style=\"font-size: clamp(1.8rem, 2.2vw, 2.7rem); margin-bottom: 16px;\">Strategic clarity for teams that are ready to scale.</h2>\n"
            + "              <p class=\"subtitle\" style=\"margin-bottom: 0;\">We blend advisory expertise with practical implementation support, giving you a partner that can diagnose issues, design solutions, and help your team execute with confidence.</p>\n"
            + "              <ul class=\"check-list\">\n"
            + "                <li>Executive-level guidance rooted in real operating experience.</li>\n"
            + "                <li>Custom roadmaps tailored to your market, growth stage, and goals.</li>\n"
            + "                <li>Clear reporting, measurable outcomes, and accountable next steps.</li>\n"
            + "              </ul>\n"
            + "            </div>\n"
            + "            <div class=\"feature-grid\">\n"
            + "              <article class=\"glass glass-card feature-card\">\n"
            + "                <h3>Market Insight</h3>\n"
            + "                <p>Better positioning through sharper customer understanding and competitive intelligence.</p>\n"
            + "              </article>\n"
            + "              <article class=\"glass glass-card feature-card\">\n"
            + "                <h3>Execution Focus</h3>\n"
            + "                <p>Systems that turn strategy into clear action across sales, marketing, and operations.</p>\n"
            + "              </article>\n"
            + "              <article class=\"glass glass-card feature-card\">\n"
            + "                <h3>Revenue Design</h3>\n"
            + "                <p>Improved conversion paths and pipeline quality with data-backed decision making.</p>\n"
            + "              </article>\n"
            + "              <article class=\"glass glass-card feature-card\">\n"
            + "                <h3>Leadership Support</h3>\n"
            + "                <p>Sharper collaboration, communication, and decision processes for leadership teams.</p>\n"
            + "              </article>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "        <section id=\"process\" class=\"section\">\n"
            + "          <div class=\"section-head\">\n"
            + "            <span class=\"eyebrow\">Our process</span>\n"
            + "            <h2>A simple framework that keeps momentum high.</h2>\n"
            + "          </div>\n"
            + "          <div class=\"process-grid\">\n"
            + "            <article class=\"glass glass-card process-card\">\n"
            + "              <div class=\"process-step\">01</div>\n"
            + "              <h3>Discover</h3>\n"
            + "              <p>We evaluate your goals, challenges, customer journey, and current performance signals.</p>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card process-card\">\n"
            + "              <div class=\"process-step\">02</div>\n"
            + "              <h3>Diagnose</h3>\n"
            + "              <p>We identify friction points, bottlenecks, and strategic opportunities with clear priorities.</p>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card process-card\">\n"
            + "              <div class=\"process-step\">03</div>\n"
            + "              <h3>Design</h3>\n"
            + "              <p>We build a practical roadmap with measurable milestones and accountable ownership.</p>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card process-card\">\n"
            + "              <div class=\"process-step\">04</div>\n"
            + "              <h3>Scale</h3>\n"
            + "              <p>We help your team implement, monitor, and refine the systems that drive momentum.</p>\n"
            + "            </article>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "        <section class=\"section\">\n"
            + "          <div class=\"glass glass-panel\">\n"
            + "            <div class=\"metrics-wrap\">\n"
            + "              <div class=\"glass-card metric\">\n"
            + "                <strong>120+</strong>\n"
            + "                <span>client engagements</span>\n"
            + "              </div>\n"
            + "              <div class=\"glass-card metric\">\n"
            + "                <strong>18</strong>\n"
            + "                <span>industries supported</span>\n"
            + "              </div>\n"
            + "              <div class=\"glass-card metric\">\n"
            + "                <strong>9.4/10</strong>\n"
            + "                <span>average client rating</span>\n"
            + "              </div>\n"
            + "              <div class=\"glass-card metric\">\n"
            + "                <strong>6 wks</strong>\n"
            + "                <span>average time to launch</span>\n"
            + "              </div>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "        <section class=\"section\">\n"
            + "          <div class=\"section-head\">\n"
            + "            <span class=\"eyebrow\">Client feedback</span>\n"
            + "            <h2>Trusted by teams who value clarity and results.</h2>\n"
            + "          </div>\n"
            + "          <div class=\"testimonials-grid\">\n"
            + "            <article class=\"glass glass-card testimonial\">\n"
            + "              <div class=\"quote-mark\">“</div>\n"
            + "              <p>Northstar helped us restructure our growth plan and gave our leadership team a much clearer path to scale.</p>\n"
            + "              <div class=\"testimonial-footer\">\n"
            + "                <div class=\"person\">\n"
            + "                  <div class=\"avatar\">AS</div>\n"
            + "                  <div>\n"
            + "                    <strong>Alicia Stone</strong><br />\n"
            + "                    <small>COO, Harbor &amp; Co.</small>\n"
            + "                  </div>\n"
            + "                </div>\n"
            + "              </div>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card testimonial\">\n"
            + "              <div class=\"quote-mark\">“</div>\n"
            + "              <p>Their ability to blend strategic thinking with real operational execution made a major difference for our team.</p>\n"
            + "              <div class=\"testimonial-footer\">\n"
            + "                <div class=\"person\">\n"
            + "                  <div class=\"avatar\">DM</div>\n"
            + "                  <div>\n"
            + "                    <strong>Daniel Moore</strong><br />\n"
            + "                    <small>Founder, Apex Systems</small>\n"
            + "                  </div>\n"
            + "                </div>\n"
            + "              </div>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card testimonial\">\n"
            + "              <div class=\"quote-mark\">“</div>\n"
            + "              <p>We finally had a partner who could help us improve performance without adding unnecessary complexity.</p>\n"
            + "              <div class=\"testimonial-footer\">\n"
            + "                <div class=\"person\">\n"
            + "                  <div class=\"avatar\">JK</div>\n"
            + "                  <div>\n"
            + "                    <strong>Jasmine Kim</strong><br />\n"
            + "                    <small>VP Marketing, Luma Group</small>\n"
            + "                  </div>\n"
            + "                </div>\n"
            + "              </div>\n"
            + "            </article>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "        <section id=\"pricing\" class=\"section\">\n"
            + "          <div class=\"section-head\">\n"
            + "            <span class=\"eyebrow\">Pricing</span>\n"
            + "            <h2>Flexible engagement options for growing teams.</h2>\n"
            + "          </div>\n"
            + "          <div class=\"pricing-grid\">\n"
            + "            <article class=\"glass glass-card price-card\">\n"
            + "              <h3>Starter Advisory</h3>\n"
            + "              <p>For early-stage teams that need strategic direction.</p>\n"
            + "              <div class=\"price\">$1,200<span style=\"font-size: 0.9rem; color: var(--text-3);\">/mo</span></div>\n"
            + "              <ul>\n"
            + "                <li>Monthly strategy sessions</li>\n"
            + "                <li>Growth planning support</li>\n"
            + "                <li>Priority email guidance</li>\n"
            + "              </ul>\n"
            + "              <a class=\"glass-button secondary\" href=\"#contact\" style=\"margin-top: 22px;\">Get started</a>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card price-card featured\">\n"
            + "              <div class=\"featured-badge\">Most Popular</div>\n"
            + "              <h3>Growth Partnership</h3>\n"
            + "              <p>For businesses ready to align strategy with execution.</p>\n"
            + "              <div class=\"price\">$2,900<span style=\"font-size: 0.9rem; color: var(--text-3);\">/mo</span></div>\n"
            + "              <ul>\n"
            + "                <li>Everything in Starter</li>\n"
            + "                <li>Weekly strategic syncs</li>\n"
            + "                <li>Implementation planning</li>\n"
            + "                <li>Performance reporting</li>\n"
            + "              </ul>\n"
            + "              <a class=\"glass-button primary\" href=\"#contact\" style=\"margin-top: 22px;\">Book a consult</a>\n"
            + "            </article>\n"
            + "            <article class=\"glass glass-card price-card\">\n"
            + "              <h3>Executive Sprint</h3>\n"
            + "              <p>For focused transformation initiatives and leadership alignment.</p>\n"
            + "              <div class=\"price\">$5,400<span style=\"font-size: 0.9rem; color: var(--text-3);\">/engagement</span></div>\n"
            + "              <ul>\n"
            + "                <li>Deep-dive assessment</li>\n"
            + "                <li>Prioritized roadmap</li>\n"
            + "                <li>Leadership workshop</li>\n"
            + "                <li>Execution tracking</li>\n"
            + "              </ul>\n"
            + "              <a class=\"glass-button secondary\" href=\"#contact\" style=\"margin-top: 22px;\">Request proposal</a>\n"
            + "            </article>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "        <section id=\"contact\" class=\"section\">\n"
            + "          <div class=\"glass cta-box\">\n"
            + "            <div>\n"
            + "              <h3>Ready to accelerate your next phase of growth?</h3>\n"
            + "              <p>Tell us where you want to go, and we’ll help you map the path forward.</p>\n"
            + "            </div>\n"
            + "            <a class=\"glass-button primary\" href=\"mailto:hello@northstaradvisory.com\">hello@northstaradvisory.com</a>\n"
            + "          </div>\n"
            + "        </section>\n"
            + "      </main>\n"
            + "      <footer class=\"glass glass-panel\" style=\"margin-top: 24px;\">\n"
            + "        <div class=\"footer-grid\">\n"
            + "          <div>\n"
            + "            <div class=\"mini-logo\">\n"
            + "              <span class=\"brand-mark\"></span>\n"
            + "              <strong>Northstar Advisory</strong>\n"
            + "            </div>\n"
            + "            <p>Strategic advisory and growth systems for companies that want a clear, disciplined path to scale.</p>\n"
            + "          </div>\n"
            + "          <div>\n"
            + "            <h4>Company</h4>\n"
            + "            <ul class=\"footer-links\">\n"
            + "              <li><a href=\"#about\">About</a></li>\n"
            + "              <li><a href=\"#services\">Services</a></li>\n"
            + "              <li><a href=\"#process\">Process</a></li>\n"
            + "            </ul>\n"
            + "          </div>\n"
            + "          <div>\n"
            + "            <h4>Resources</h4>\n"
            + "            <ul class=\"footer-links\">\n"
            + "              <li><a href=\"#pricing\">Pricing</a></li>\n"
            + "              <li><a href=\"#contact\">Contact</a></li>\n"
            + "              <li><a href=\"#\">Insights</a></li>\n"
            + "            </ul>\n"
            + "          </div>\n"
            + "          <div>\n"
            + "            <h4>Connect</h4>\n"
            + "            <ul class=\"footer-links\">\n"
            + "              <li><a href=\"mailto:hello@northstaradvisory.com\">Email</a></li>\n"
            + "              <li><a href=\"#\">LinkedIn</a></li>\n"
            + "              <li><a href=\"#\">Book a call</a></li>\n"
            + "            </ul>\n"
            + "          </div>\n"
            + "        </div>\n"
            + "        <div class=\"footer-note\" style=\"margin-top: 20px; padding-top: 18px; border-top: 1px solid rgba(255,255,255,0.14);\">\n"
            + "          <span>© 2026 Northstar Advisory</span>\n"
            + "          <span>Built for confident business growth.</span>\n"
            + "        </div>\n"
            + "      </footer>\n"
            + "    </div>\n"
            + "  </body>\n"
            + "</html>\n";
    }
}
